import Head from 'next/head'

import HeadingOne from '@/components/ui/HeadingOne'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-screen bg-black justify-center items-center">
          <HeadingOne intent="thin">NextJS Boilerplate 🚀</HeadingOne>
        </div>
      </main>
    </>
  )
}
