name: Docker

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.prettierrc.json'
      - '.gitattributes'
      - '.editorconfig'
      - '.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          push: false
